### ISSUE TITLE
Vulgarisation du projet

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/joinDjolof#12]
Hello @EmmanuelDiokh 
Beaucoup d'actualité sur nos libertés chez tweets une bonne opportunité pour lancer le space histoire de vulgarisé le pourquoi du projet

- [ ] Titre ?
- [ ] Date ?
- [ ] Invités ?
- [x] Affiche ?
- [x] Communication ?

**Comment by EmmanuelDiokh** [comment]
Hello grand 
Sorry pour le retard.
Pour ma com, je pense qu'il nous faut démarrer pour que les autres nous rejoignent

**Comment by EmmanuelDiokh** [comment]
Pouvons nous avoir qu'un pour quelques visuels et faire épouser l'idée. Si on a un article je propose qu'on publie déjà dans social netlink

**Comment by dofbi** [comment]
Salaam @EmmanuelDiokh 
Merci pour ces suggestions, pourquoi pas résumer le contenue du site https://joindjolof.netlify.app
Pour la rédaction de cet article et mettre l'accent sur l'appel à action pour les dons
Merci
