### ISSUE TITLE
Co-rédaction des règles Mastodon 🇸🇳

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/joinDjolof#2]
# Votre instance vos règles 🇸🇳

Nous vous invitons à Co-écrire ces règles ⚖️ ensemble

**Comment by dofbi** [comment]
Hello @EmmanuelDiokh
Je viens d'ajouter une pas [Nos règles !](https://github.com/Code-for-Senegal/joinDjolof/blob/main/src/contents/nos-regles.md) elle attends tes inputs 🙏🏾

**Comment by dofbi** [comment]
Salut @EmmanuelDiokh 
Des proposition pour la partie **Modération active contre le racisme, le sexisme, l'homophobie et la transphobie**
Il est important qu'on avance petit à petit.
Pourquoi pas host un space de notre côté en attendant le DivanCitoyen ?
Un espace d'avant bouche ?
Avec les basics de Mastodon
Et le pourquoi

**Comment by EmmanuelDiokh** [comment]
Super pour moi
On travaille alors sur le plan du space les thèmes à traiter.


*Emmanuel M .DIOKH*
*DPO, JURISTICOM, LAW MANAGER *
*TMT (technologies-medias-telecoms) *
*IP/IT (intellectual property-information technology)  *
*DROIT-TIC-TELECOM-JURISTICOM
<https://juristicom.blogspot.sn/?view=magazine>*





Le jeu. 1 déc. 2022 à 10:52, Mamadou Diagne ***@***.***> a
écrit :

**Comment by dofbi** [comment]
Hello @EmmanuelDiokh 
- [x] Une date de retenue ?
- [ ] Un Titre ?

**Comment by EmmanuelDiokh** [comment]
Vendredi 9

**Comment by dofbi** [comment]
Salaam grand @EmmanuelDiokh 
C'est aujourd'hui lien ?

**Comment by EmmanuelDiokh** [comment]
Yep grand on commence ce soir et durant le weekend pour avancer
