### ISSUE TITLE
Levée de fonds

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/joinDjolof#3]
## Votre instance vos coûts

Mastodon est entièrement libre et ouvert, mais l’hébergement d’un serveur, l’achat d’un nom de domaine Représente un certain coût

Mastodon est conçu pour être une plateforme sans publicité. Pour cette raison, nous avons besoin financement participatif, mais aussi de travailleurs de volontaires.

Nous avons lancé un premier compagnon de [Levée de fonds](https://maajjal.com/app/campagnes/djolof) pour un fond de démarrage.

**Comment by dofbi** [comment]
Dernier update non pour le Sénégal

> Est-ce possible d'avoir le github sponsoring ? @dofbi t'as vérifié cela ?

**Comment by mamby** [comment]
OK

**Comment by dofbi** [comment]
Salaam @mamby
Après plusieurs tentatives soldées d'échec sur la plateforme https://maajjal.com/app/campagnes/djolof
Il faut Tester une autre plateforme 🙏🏾

**Comment by mamby** [comment]
On y va !

**Comment by dofbi** [comment]
Hello @mamby 
Je viens d'ajouter le lien https://koparexpress.com/apps/collectes/5m2l06uj
On peut lancer les Teste Merci

**Comment by mamby** [comment]
good job!

**Comment by dofbi** [comment]
@mamby est possible d'update l'image
![Capture d’écran du 2022-11-18 12-14-40](https://user-images.githubusercontent.com/84446/202702990-e4392433-1cec-4ec3-aa8f-4d6f677f05f4.png)

Par cette version 
![mastodon-sn](https://user-images.githubusercontent.com/84446/202703928-b086808f-48ea-4eed-8327-c70d8f8ee006.png)

**Comment by mamby** [comment]
Pas dEdit ! je vais leur envoyé un message pour voir.

**Comment by mamby** [comment]
11 800 FCFA au 30 novembre 2022.

![IMG_20221130_191551.jpg](https://user-images.githubusercontent.com/442257/204876678-9ddd391d-f169-4614-97df-316d8c73ffc3.jpg)

![IMG_20221130_191618.jpg](https://user-images.githubusercontent.com/442257/204876707-e9f4f864-bba1-4c66-8fd3-4d0f3e3605f1.jpg)

**Comment by dofbi** [comment]
Salaam @mamby 
Merci pour l'update après deux semaines, pas trop de support, nous devons travailler plus la communication. Mais pourquoi pas aussi nous tourner vers les plateformes internationales aussi ?

**Comment by mamby** [comment]
Oui why not! je vais regarder ça.

**Comment by dofbi** [comment]
Hello @mamby 
Tu as validé une plateforme ?

**Comment by mamby** [comment]
> Hello @mamby 
> Tu as validé une plateforme ?

Pas encore ! je le ferais ce weekend !

**Comment by mamby** [comment]
on peut essayer https://www.gofundme.com/ pour plus d'expostition!
What do you think?

**Comment by dofbi** [comment]
Salaam @mamby 
Oui pourquoi, partage le lien dès que crée merci

**Comment by mamby** [comment]
Pas dispo pour le Sénégal à mon niveau ! je cherche un autre. 😔

**Comment by dofbi** [comment]
Hello @mamby Si tu peux manager hors Sénégal ou quelqu'un d'autre pourquoi pas

**Comment by mamby** [comment]
> Hello @mamby Si tu peux manager hors Sénégal ou quelqu'un d'autre pourquoi pas

Pas possible pour moi ! si quelqu'un d'autre peut le faire ça sera cool pour une bonne exposition ! sinon j'essaie avec d'autres plateformes
