### ISSUE TITLE
Déploiement du serveur

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/joinDjolof#8]
Architecture de notre serveur
![harchitecture-2022-11-21-1527](https://user-images.githubusercontent.com/84446/203365153-5bc13c69-9753-44f1-b8d1-afc54e6b818e.svg)

- [ ] Nom de domaine
- [ ] Linode 2 GB
- [ ] Cloudron
- [ ] SMTP
- [ ] Mastodon
- [ ] Amazon S3 Object storage provider

**Comment by ByNatO** [comment]
Bonjour Mamadou. C'est intéressant. Amazon S3 joue le rôle de backup ici?

**Comment by dofbi** [comment]
Oui, une des recommandations pour facilité le scaling 
> Bonjour Mamadou. C'est intéressant. Amazon S3 joue le rôle de backup ici?
